### PR TITLE
Relax Guzzle version strictness

### PR DESCRIPTION
**Pull request by manavo**

### CODE REVIEW

**Comment by ricbra** [comment]
Hi @manavo thanks for your PR.

I'm not against loosening the version constraint, but with the current changes composer installs v3.9.2 which breaks the tests.

Could you take a look at the tests? Apparently the token gets lost in <code>Collection::fromConfig($config, $default, $required);</code>

**Comment by manavo** [comment]
Sorry, didn't see it breaks the tests. I'll have a look at the tests and see if I can fix it!

**Comment by ricbra** [comment]
Cool, if you need any help let me know.

**Comment by manavo** [comment]
The test that's failing is ```testFactoryInitializesClientWithIdentification```. In that test, it sets the auth type to be 'oauth'. Is that correct though? I think it should be 'http', and that then fixes the test as well.

**Comment by ricbra** [comment]
No thats wrong indeed. It should be "http", wonder why the tests didn't fail in the past...

Could you apply that patch? I'll be happy to merge it when all is green again at Travis.

**Comment by manavo** [comment]
I think it passed previously because 'token' is there with a default of null.

Guzzle changed the way the merging of config and defaults happens in the Collection command (Collection::fromConfig). Which I think means that keys with null values now get removed.

Just pushed the change, the Travis build should work now :)

**Comment by ricbra** [comment]
Hi @manavo 

I didn't ment to bump version to 3.9, just to let the author of that PR know we're loosening the constraint in this PR. 

So could you please drop your last commit, and then I'll merge it!

Btw. if possible, please open separate PR's for stuff you fix so things keep clean :)

**Comment by manavo** [comment]
OK, put it back down to 3.3.

Yeah, sorry for the extra things I pushed in, being a bit lazy :) Just figures it's small typos, so not worth a separate PR. I'll keep in mind for other times though!

Thanks!

**Comment by ricbra** [comment]
Allright, thanks @manavo

**Pull request merged**
